---
title: "graficos-likert"
author: "Mateus Reis"
date: "31/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(likert)
library(kableExtra)

db<-read_csv("/home/mateus/Dropbox/TCC_mateus_reis/TCC/PROGRAMAÇÃO/tcc-sucesso-profissional-professor-matem-tica-df/base_tcc.csv")


Graf.likert<-function(lik){
  
  
  lik[ , 1:length(lik)] <- lapply(  lik[ , 1:length(lik)], function(x){ factor(x, 
                                                                                     levels = c('Discordo totalmente.', 
                                                                                                'Discordo parcialmente.', 
                                                                                                'Nem concordo e nem discordo.',
                                                                                                'Concordo parcialmente.', 
                                                                                                'Concordo totalmente.'), 
                                                                                     labels = c('Discordo', 
                                                                                                'Discordo', 
                                                                                                'Nem concordo e nem discordo.',
                                                                                                'Concordo', 
                                                                                                'Concordo'))})
  lik.1<-likert(as.data.frame(lik))
  
  return(plot(lik.1,wrap = 30) + theme(axis.text.y = element_text(size="10")))
  
}

  ## A função abaixo separa por instituição

Graf.likert.cat<-function(lik,categoria){
  

  lik[ , 1:length(lik)] <- lapply(  lik[ , 1:length(lik)], function(x){ factor(x,
                                                                                     levels = c('Discordo totalmente.',
                                                                                                'Discordo parcialmente.',
                                                                                                'Nem concordo e nem discordo.',
                                                                                                'Concordo parcialmente.',
                                                                                                'Concordo totalmente.'),
                                                                                     labels = c('Discordo',
                                                                                                'Discordo',
                                                                                                'Nem concordo e nem discordo.',
                                                                                                'Concordo',
                                                                                                'Concordo'))})
  
  
  categoria[ , 1:length(categoria)] <- lapply(  categoria[ , 1:length(categoria)], function(x){ factor(x, 
                                                                                     levels = c('Na Secretaria de Educação do Distrito Federal', 
                                                                                                'Trabalha na Rede Federal (Instituto Federal de Brasília)'), 
                                                                                     labels = c('SEEDF', 
                                                                                                'IFB'))})
  df<-cbind.data.frame(categoria,lik)
  
  if(length(df)>2){
      return(plot(likert(df[,c(2:length(df))],grouping=df[,1]))+ theme(axis.text.y = element_text(size="7")))#Só funcionou desse modo. Só Deus e o desenvolvedor sambem o porquê.Mas aparentemente tem que estar no mesmo data frame e a função não aceita outro tipo de entrada.
  }else{
    return(df)
  }

}


```




# Aspectos de competência profissional
```{r}
Comp.profissional<-db[,c(15:16)]
Graf.likert(Comp.profissional)
```


```{r}
Comp.profissional<-db[,c(17:18)]
Graf.likert(Comp.profissional)
```


```{r}
Graf.likert.cat(db[,c(15:16)],db[,4])
```

```{r}
Graf.likert.cat(db[,c(17:18)],db[,4])
```


# Relações Interpessoais

```{r}
Rel.Int<-db[,c(21:22)]
Graf.likert(Rel.Int)
```

```{r}
Rel.Int<-db[,c(19:20)]
Graf.likert(Rel.Int)
```

```{r}
Graf.likert.cat(db[,c(19:20)],db[,4])
```

```{r}
Graf.likert.cat(db[,c(21:22)],db[,4])
```


# Riscos e iniciativas

```{r}
Ris.Ini<-db[,c(23:24)]  
Graf.likert(Ris.Ini)
```

```{r}
Ris.Ini<-db[,c(25:26)]  
Graf.likert(Ris.Ini)
```

```{r}
Graf.likert.cat(db[,c(23:24)],db[,4])

```
  

```{r}
Graf.likert.cat(db[,c(25:26)],db[,4])

```
  
# Interação com alunos

```{r}
Int.Alun<-db[,c(27:28)]  
Graf.likert(Int.Alun)
```


```{r}
Int.Alun<-db[,c(29:31)]  
Graf.likert(Int.Alun)
```


```{r}
Graf.likert.cat(db[,c(27:28)],db[,4])
```

```{r}
Graf.likert.cat(db[,c(29:31)],db[,4])
```

# Autossatisfação

```{r}
Autossatisfacao<-db[,c(32:34)]  
Graf.likert(Autossatisfacao)

```


```{r}
Autossatisfacao<-db[,c(35:37)]  
Graf.likert(Autossatisfacao)

```



```{r}
Graf.likert.cat(db[,c(32:34)],db[,4])
```

```{r}
Graf.likert.cat(db[,c(35:37)],db[,4])
```


# Autoaceitação

```{r}
Autoaceitacao<-db[,c(38:40)]
Graf.likert(Autoaceitacao)
```

```{r}
Autoaceitacao<-db[,c(41:43)]
Graf.likert(Autoaceitacao)
```



```{r}
Graf.likert.cat(db[,c(38:40)],db[,4])
```


```{r}
Graf.likert.cat(db[,c(41:43)],db[,4])
```

# Estrutura e localização da instituição de trabalho

```{r}
Local.Trab<-db[,c(44:45)]
Graf.likert(Local.Trab)
```

```{r}
Local.Trab<-db[,c(46:47)]
Graf.likert(Local.Trab)
```



```{r}
Graf.likert.cat(db[,c(44:45)],db[,4])
```


```{r}
Graf.likert.cat(db[,c(46:47)],db[,4])
```

# Sucesso profissional

```{r}
Sucesso.Prof<-db[,49]
Graf.likert(Sucesso.Prof)
```



```{r}
a<-Graf.likert.cat(db[,49],db[,4])

plot(likert(as.data.frame(a$`Atualmente me considero um profissional bem sucedido na área de educação`),grouping=a$`Atualmente considere sua maior carga horária`))+ theme(axis.text.y = element_text(size="10"))

```


